# Generated by Django 6.0.5 on 2026-06-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_coupon_rename_reach_time_bus_reach_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookings',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='refund_status',
            field=models.CharField(choices=[('not_applied', 'Not Applied'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
